meta_product_name: "SpareSeat"
meta_title: "SpareSeat - A new way to purchase tickets for your favourite events."
meta_description: "Buy and sell tickets to sporting events whilst meeting other likeminded fans!"
meta_image: "wembley.png"
twitter_account: "@treecey98"
